dica = [   
			'Clique no balão para o proximo passo', 
			'Hidrocarbonetos nos quais todas as ligações carbono-carbono são ligações simples, são chamados alcanos. (Solomons, p.110)',
		    'Cada hidrocarboneto depende do seu composto para ter um nome específico segundo a IUPAC.',     
			'Nomenclatura: Quantia de carbonos e seus prefixos: 1 (Met), 2 (Et), 3 (Prop), 4 (But), 5 (Pent), 6 (Hex), 7 (Hept), 8 (Oct), 9 (Non), 10 (Dec).', 
			'Todos os Alcanos (ligações simples) possuem em sua nomenclatura o infixo AN, por ex: metANo.',
			'O mais simples dos alcenos é o eteno (ou etileno), este se apresenta como um gás incolor, e insolúvel na água.',
			'Alcenos até 4 Carbonos são gases à temperatura ambiente.',
			'Todos os Alcenos (duplas ligações) possuem em sua nomenclatura o infixo EN por ex: PentENo.',
			'Para acertar a nomenclatura, deve-se começar a numerar os cabonos, a partir do carbono mais próximo à insaturação.',
			'Todos os Alcinos (triplas ligações) possuem em sua nomenclatura o infixo IN, por ex: ButINo.',
			'A fórmula geral dos Alcinos é CnH2n-2.',
			'A condição par que se identifique um Alcino  é que ele possua pelo menos uma ligação tripla entre átomos de Carbono.',
			'Todos os Alcoois (O-H) possuem em sua nomenclatura o sufixo OL, por ex: ButanOL.',
			'Os alcoóis são compostos cujas moléculas têm um grupo hidroxila ligado a um átomo de carbono saturado. (Solomons p. 405)',
			'Para fazer a nomenclatura de alcoóis começa-se a numerar os carbonos a partir do carbono mais próximo à hidroxila.',
			'O grupo hidroxila tem preferência sobre as ligações duplas e triplas, para decidir qual grupo funcional determinará o sufixo. (Solomons p. 406)',
			'Todos os Éteres (C-O-C) possuem em sua nomenclatura o sufixo “Oxi ” seguido da segunda palavra com sufixo “ano” por ex: Ex.: metoxietano.',
			'Os Éteres apresentam ligações C-O-C definidas por um ângulo entre as ligações de aproximadamente 120°.',
			'São caracterizados pela presença de um átomo de oxigênio ligado a dois (e entre estes) de carbono da cadeia.',
			'Para a nomenclatura dos ésteres, temos sempre o sufixo ATO + de + nome do radical.',
			'Na nomencura , temos por exemplo: CH3CH2COO - CH2CH3 → propanoato de etila.',
			'Fabricantes de alimentos e de bebidas utilizam estes ésteres como aditivos para intensificar o sabor ou o odor de sobremesas e bebidas.',
			'Em química orgânica, um composto cíclico é um composto no qual uma série de átomos de carbono são conectados formando um laço ou anel.',
			'Primeiramente denomina-se o nome do substituinte, depois se denomina a palavra benzeno.',
			'A única diferença entre os hidrocarbonetos de cadeia aberta e os de cadeia cíclica é a presença do prefixo “ciclo”.',
			'Compostos aromáticos possuem um ou mais anéis benzênicos nos quais existem ligações simples e duplas alternadamente.',
			'As cetonas são compostos orgânicos caracterizados pela presença do grupamento —C(=O)—, carbonila, ligado a dois radicais orgânicos. ',
			'A nomenclatura desses compostos é feita fundamentada na dos hidrocarbonetos, apenas trocando o sufixo "o" por "ona". ',
			'Quando houver ambigüidade na posição do grupo carbonila, esta deve ser indicada antes do sufixo, da mesma maneira que em outras funções orgânicas.',
			'R e R` podem também estar unidos. Nesse caso, compõem um ciclo (cetonas cíclicas).',
			'Aminas são derivadas de compostos orgânico de amônia.',
			'Existem aminas primárias, secundárias e terciárias. Ex: R—NH—R = amina secundária.',
			'Amina secundária- prefixo di. Amina terciária- prefixo tri. O sufixo do composto é “amina”.',
			'Os aminoácidos- que são as estruturas das proteínas- contém sempre um grupo amino e um grupo  carboxilo.',
			'Aminas podem ser : Não-substituídas- Prefixo + Infixo + Amida; Monossubstituídas- N + nome do radical ou N,N + nome dos radicais + prefixo + infixo + amida ou Dissubstituídas-: N + nome do radical ou N,N + nome dos radicais + prefixo + infixo + amida.',
			'A presença do grupo C=O confere às amidas um caráter polar.  O nylon é uma poliamida muito importante dentre os polímeros.',
			'As amidas secundárias e cíclicas são chamadas imidas.',
			'Amidas são os derivados de oxiácidos  no qual uma hidroxila ácida -OH é substituída por um grupo amina -NH2',
			'Amidas são caracterizadas pela molécula(NH3) e pela ligação direta do nitrogênio com um grupo carbonila (C=O).',
			'As moléculas de amida, em geral, possuem caráter polar por apresentarem o grupo carbonilico. Assim, são solúveis em água, embora possam apresentar certa solubilidade em solventes orgânicos.',		
		]

